WITH TRIPS AS (

select
	RIDE_ID,
	DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
	START_STATIO_ID                AS START_STATION_ID,
    TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS,
	MEMBER_CSUAL                    AS MEMBER_CASUAL

from {{ ref('stg_bike') }}

)


select
*
from TRIPS